Repository amida-tech/orange-api, pull requests merged in 2019-01, with the labels that each got.

#146 Changing email body and subject
  views/registration/email_body.handlebars
  views/registration/email_subject.handlebars
Labels: ready for review

#149 remove crashing log statement, reformatting
  lib/controllers/journal.js
Labels: on dev, test done (dev), test team n/a

#151 when default patient info changes, update user info too
  lib/models/patient/patient.js
  lib/models/user/user.js
Labels: deploy to dev

#153 Removing cycle shifting in display field
  lib/models/schedule/schedule.js
Labels: deploy to dev

#155 mock data script: clean up logging, including passwords.
  scripts/demoScripts/create-demo-data.sh
  scripts/demoScripts/reportsMockScript.js
Labels: ready for review
